#!/usr/bin/env python

import boto

s3 = boto.connect_s3()
bucket = s3.get_bucket('config.company.services')
key = bucket.get_key('the-app')

key.set_contents_from_string('''
export APP_DB_USER=nodeappuser
export APP_DB_PASS=password
export APP_DB_HOST=localhost
export APP_DB_PORT=5432
export APP_DB_NAME=nodeappdb
''')
