#!/usr/bin/env node

var AWS = require('aws-sdk');
var AwsStack = require('./aws-stack');
var AWSP = require('./promise-aws');

var creds = new AWS.SharedIniFileCredentials({
  profile: 'company'
});
AWS.config.credentials = creds;

var s3 = new AWSP.S3({
  region: 'ap-southeast-2'
});

AwsStack.findS3BucketsTagged('online-tax').
  then(function(buckets) {
    return buckets[0]
  }).
  then(function(bucket) {
    return s3.putObject({
      Bucket: bucket.bucketName,
      Key: 'the-app/latest.config',
      Body: 'export APP_DB_USER=nodeappuser\n' +
            'export APP_DB_PASS=password\n' +
            'export APP_DB_HOST=localhost\n' +
            'export APP_DB_PORT=5432\n' +
            'export APP_DB_NAME=nodeappdb\n'
    })
  })
  .then(function() {
    console.log('Config updated')
  }).
  catch(function(err) {
    console.log('Failed to upload config', err)
  })
